CREATE DATABASE IF NOT EXISTS ufo_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'ufo_user'@'127.0.0.1' IDENTIFIED BY 'k8X2aP4mQ9sV7nT3uR1yC6hL';
CREATE USER IF NOT EXISTS 'ufo_user'@'localhost' IDENTIFIED BY 'k8X2aP4mQ9sV7nT3uR1yC6hL';
GRANT ALL PRIVILEGES ON ufo_db.* TO 'ufo_user'@'127.0.0.1';
GRANT ALL PRIVILEGES ON ufo_db.* TO 'ufo_user'@'localhost';
FLUSH PRIVILEGES;
