<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        if (!Schema::hasTable('workflow_reference_values')) {
            return;
        }

        $domain = 'ui_text';

        $records = [
            'kmh_dashboard_chart_title' => 'Grafik Kegiatan Bulanan',
            'kmh_dashboard_quick_actions_title' => 'Quick Actions',
            'kmh_dashboard_quick_action_review' => 'Review Kegiatan',
            'kmh_dashboard_quick_action_announcement' => 'Buat Pengumuman',
            'kmh_dashboard_upcoming_events_title' => 'Kegiatan Mendatang',
            'kmh_dashboard_upcoming_empty_title' => 'Belum ada kegiatan mendatang',
            'kmh_dashboard_upcoming_empty_message' => 'Data kegiatan akan tampil setelah event terdaftar.',
            'kmh_dashboard_recent_announcements_title' => 'Pengumuman Terbaru',
            'kmh_common_view_all' => 'Lihat Semua',
            'kmh_dashboard_table_col_title' => 'Judul Pengumuman',
            'kmh_dashboard_table_col_date' => 'Tanggal',
            'kmh_dashboard_table_col_status' => 'Status',
            'kmh_dashboard_recent_empty' => 'Belum ada pengumuman terbaru.',
            'kmh_notification_total' => 'Total Notifikasi',
            'kmh_notification_unread' => 'Belum Dibaca',
            'kmh_notification_filter_title' => 'Filter Notifikasi',
            'kmh_notification_filter_showing_items' => 'Menampilkan item:',
            'kmh_notification_summary_prefix' => 'Menampilkan',
            'kmh_notification_summary_suffix' => 'notifikasi untuk filter',
            'kmh_notification_reset_filter' => 'Reset Filter',
            'kmh_notification_open_submission_review' => 'Buka Review Pengajuan',
            'kmh_notification_detail_button' => 'Lihat Detail',
            'kmh_notification_empty_state' => 'Belum ada notifikasi untuk filter ini.',
            'kmh_contact_hero_title' => 'Kontak Pengurus UKM',
            'kmh_contact_hero_subtitle' => 'Daftar kontak pengurus organisasi mahasiswa Universitas Klabat',
            'kmh_contact_search_placeholder' => 'Cari organisasi berdasarkan nama, kategori, atau bidang...',
            'kmh_contact_search_aria' => 'Cari organisasi berdasarkan nama, kategori, atau bidang',
            'kmh_contact_total_org_label' => 'Total Organisasi',
            'kmh_contact_bem_label' => 'BEM',
            'kmh_contact_ukm_label' => 'UKM',
            'kmh_contact_unavailable' => 'Kontak belum tersedia',
            'kmh_email_unavailable' => 'Email belum tersedia',
            'kmh_contact_empty_state' => 'Belum ada data kontak pengurus UKM.',
            'kmh_contact_search_empty_state' => 'Tidak ada organisasi yang cocok dengan kata kunci pencarian.',
            'kmh_calendar_title' => 'Kalender Kegiatan Kampus',
            'kmh_calendar_subtitle' => 'Kelola dan pantau semua kegiatan akademik & non-akademik',
            'kmh_calendar_add_activity' => 'Tambah Kegiatan',
            'kmh_calendar_filter_category' => 'Filter Kategori',
            'kmh_calendar_search_label' => 'Cari Kegiatan',
            'kmh_calendar_search_placeholder' => 'Cari nama kegiatan...',
            'kmh_calendar_legend_label' => 'Legend:',
            'kmh_calendar_all_activities' => 'Semua Kegiatan',
            'kmh_calendar_month_view' => 'Bulan',
            'kmh_calendar_list_view' => 'List',
            'kmh_calendar_more_suffix' => 'lainnya',
            'kmh_calendar_table_col_title' => 'Judul Kegiatan',
            'kmh_calendar_table_col_org' => 'Organisasi',
            'kmh_calendar_table_col_date' => 'Tanggal',
            'kmh_calendar_table_col_location' => 'Lokasi',
            'kmh_calendar_table_col_category' => 'Kategori',
            'kmh_calendar_empty_state' => 'Tidak ada agenda untuk filter bulan ini.',
            'kmh_calendar_category_akademik' => 'Kegiatan Akademik',
            'kmh_calendar_category_organisasi' => 'Kegiatan Organisasi',
            'kmh_calendar_category_masa_tenang' => 'Masa Tidak Boleh Berorganisasi',
            'kmh_calendar_category_libur' => 'Libur Akademik',
            'kmh_calendar_category_event_besar' => 'Event Kampus Besar',
            'kmh_announcement_total_label' => 'Total Pengumuman',
            'kmh_announcement_published_label' => 'Terpublikasi',
            'kmh_announcement_scheduled_label' => 'Terjadwal',
            'kmh_announcement_draft_label' => 'Draft',
            'kmh_announcement_search_placeholder' => 'Cari judul, kategori, target, atau organisasi...',
            'kmh_announcement_search_aria' => 'Cari pengumuman',
            'kmh_common_all_statuses' => 'Semua Status',
            'kmh_announcement_create_new_button' => 'Buat Pengumuman Baru',
            'kmh_announcement_create_new_title' => 'Buat Pengumuman Baru',
            'kmh_announcement_create_new_subtitle' => 'Pengumuman baru akan masuk antrean review email',
            'kmh_announcement_account_missing_warning' => 'Belum ada akun UKM aktif. Tambahkan akun UKM terlebih dahulu pada menu Manajemen Organisasi.',
            'kmh_announcement_field_title' => 'Judul Pengumuman',
            'kmh_announcement_field_category' => 'Kategori',
            'kmh_announcement_field_target' => 'Target',
            'kmh_announcement_field_publish_date' => 'Tanggal Publish',
            'kmh_announcement_field_account' => 'Akun UKM',
            'kmh_announcement_field_account_placeholder' => 'Pilih akun',
            'kmh_announcement_field_summary' => 'Ringkasan',
            'kmh_common_save_button' => 'Simpan',
            'kmh_announcement_distribution_info_title' => 'Sistem Distribusi Email:',
            'kmh_announcement_distribution_info_body' => 'Semua pengumuman yang disetujui akan dikirim otomatis ke email resmi organisasi yang ditargetkan. Pastikan target distribusi dan ringkasan sudah benar sebelum dipublikasikan.',
            'kmh_announcement_review_email_title' => 'Review Izin Pengumuman ke Email',
            'kmh_announcement_review_email_count_suffix' => 'item menunggu review',
            'kmh_announcement_list_title' => 'Daftar Pengumuman',
            'kmh_announcement_list_count_suffix' => 'total data',
            'kmh_announcement_review_queue_empty' => 'Tidak ada antrean review email.',
            'kmh_announcement_list_empty' => 'Belum ada pengumuman.',
            'kmh_announcement_list_filter_empty' => 'Tidak ada pengumuman yang cocok dengan filter.',
            'kmh_common_review_note_placeholder' => 'Catatan (wajib jika tolak/revisi)',
            'kmh_submission_search_placeholder' => 'Cari judul, organisasi, atau catatan review...',
            'kmh_submission_search_aria' => 'Cari data pengajuan dan laporan',
            'kmh_submission_filter_scope_caption' => 'Filter berlaku untuk tabel pengajuan dan laporan.',
            'kmh_submission_table_empty' => 'Belum ada pengajuan kegiatan.',
            'kmh_submission_filter_empty' => 'Tidak ada data pengajuan yang cocok dengan filter.',
            'kmh_report_table_empty' => 'Belum ada laporan kegiatan.',
            'kmh_report_filter_empty' => 'Tidak ada data laporan yang cocok dengan filter.',
            'kmh_common_no_followup_action' => 'Tidak ada aksi lanjutan',
            'kmh_schedule_form_warning' => 'Belum ada data organisasi. Tambahkan organisasi terlebih dahulu.',
            'kmh_schedule_org_placeholder' => 'Pilih organisasi',
            'kmh_schedule_save_button' => 'Simpan Jadwal',
            'kmh_schedule_empty' => 'Belum ada jadwal kegiatan.',
        ];

        $sortBase = (int) DB::table('workflow_reference_values')
            ->where('domain', $domain)
            ->max('sort_order');

        $counter = 1;
        foreach ($records as $code => $label) {
            DB::table('workflow_reference_values')->updateOrInsert(
                ['domain' => $domain, 'code' => $code],
                [
                    'label' => $label,
                    'payload' => null,
                    'sort_order' => $sortBase + $counter,
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );

            $counter++;
        }
    }

    public function down(): void
    {
        if (!Schema::hasTable('workflow_reference_values')) {
            return;
        }

        DB::table('workflow_reference_values')
            ->where('domain', 'ui_text')
            ->whereIn('code', [
                'kmh_dashboard_chart_title',
                'kmh_dashboard_quick_actions_title',
                'kmh_dashboard_quick_action_review',
                'kmh_dashboard_quick_action_announcement',
                'kmh_dashboard_upcoming_events_title',
                'kmh_dashboard_upcoming_empty_title',
                'kmh_dashboard_upcoming_empty_message',
                'kmh_dashboard_recent_announcements_title',
                'kmh_common_view_all',
                'kmh_dashboard_table_col_title',
                'kmh_dashboard_table_col_date',
                'kmh_dashboard_table_col_status',
                'kmh_dashboard_recent_empty',
                'kmh_notification_total',
                'kmh_notification_unread',
                'kmh_notification_filter_title',
                'kmh_notification_filter_showing_items',
                'kmh_notification_summary_prefix',
                'kmh_notification_summary_suffix',
                'kmh_notification_reset_filter',
                'kmh_notification_open_submission_review',
                'kmh_notification_detail_button',
                'kmh_notification_empty_state',
                'kmh_contact_hero_title',
                'kmh_contact_hero_subtitle',
                'kmh_contact_search_placeholder',
                'kmh_contact_search_aria',
                'kmh_contact_total_org_label',
                'kmh_contact_bem_label',
                'kmh_contact_ukm_label',
                'kmh_contact_unavailable',
                'kmh_email_unavailable',
                'kmh_contact_empty_state',
                'kmh_contact_search_empty_state',
                'kmh_calendar_title',
                'kmh_calendar_subtitle',
                'kmh_calendar_add_activity',
                'kmh_calendar_filter_category',
                'kmh_calendar_search_label',
                'kmh_calendar_search_placeholder',
                'kmh_calendar_legend_label',
                'kmh_calendar_all_activities',
                'kmh_calendar_month_view',
                'kmh_calendar_list_view',
                'kmh_calendar_more_suffix',
                'kmh_calendar_table_col_title',
                'kmh_calendar_table_col_org',
                'kmh_calendar_table_col_date',
                'kmh_calendar_table_col_location',
                'kmh_calendar_table_col_category',
                'kmh_calendar_empty_state',
                'kmh_calendar_category_akademik',
                'kmh_calendar_category_organisasi',
                'kmh_calendar_category_masa_tenang',
                'kmh_calendar_category_libur',
                'kmh_calendar_category_event_besar',
                'kmh_announcement_total_label',
                'kmh_announcement_published_label',
                'kmh_announcement_scheduled_label',
                'kmh_announcement_draft_label',
                'kmh_announcement_search_placeholder',
                'kmh_announcement_search_aria',
                'kmh_common_all_statuses',
                'kmh_announcement_create_new_button',
                'kmh_announcement_create_new_title',
                'kmh_announcement_create_new_subtitle',
                'kmh_announcement_account_missing_warning',
                'kmh_announcement_field_title',
                'kmh_announcement_field_category',
                'kmh_announcement_field_target',
                'kmh_announcement_field_publish_date',
                'kmh_announcement_field_account',
                'kmh_announcement_field_account_placeholder',
                'kmh_announcement_field_summary',
                'kmh_common_save_button',
                'kmh_announcement_distribution_info_title',
                'kmh_announcement_distribution_info_body',
                'kmh_announcement_review_email_title',
                'kmh_announcement_review_email_count_suffix',
                'kmh_announcement_list_title',
                'kmh_announcement_list_count_suffix',
                'kmh_announcement_review_queue_empty',
                'kmh_announcement_list_empty',
                'kmh_announcement_list_filter_empty',
                'kmh_common_review_note_placeholder',
                'kmh_submission_search_placeholder',
                'kmh_submission_search_aria',
                'kmh_submission_filter_scope_caption',
                'kmh_submission_table_empty',
                'kmh_submission_filter_empty',
                'kmh_report_table_empty',
                'kmh_report_filter_empty',
                'kmh_common_no_followup_action',
                'kmh_schedule_form_warning',
                'kmh_schedule_org_placeholder',
                'kmh_schedule_save_button',
                'kmh_schedule_empty',
            ])
            ->delete();
    }
};
