<?php

return [
    'ui_text' => [
        'kmh_announcement_total_label' => 'Total Pengumuman',
        'kmh_announcement_published_label' => 'Terpublikasi',
        'kmh_announcement_scheduled_label' => 'Terjadwal',
        'kmh_announcement_draft_label' => 'Draft',
        'kmh_announcement_search_placeholder' => 'Cari judul, kategori, target, atau organisasi...',
        'kmh_announcement_search_aria' => 'Cari pengumuman',
        'kmh_common_all_statuses' => 'Semua Status',
        'kmh_announcement_create_new_button' => 'Buat Pengumuman Baru',
        'kmh_announcement_create_new_title' => 'Buat Pengumuman Baru',
        'kmh_announcement_create_new_subtitle' => 'Pengumuman baru akan masuk antrean review email',
        'kmh_announcement_account_missing_warning' => 'Belum ada akun UKM aktif. Tambahkan akun UKM terlebih dahulu pada menu Manajemen Organisasi.',
        'kmh_announcement_field_title' => 'Judul Pengumuman',
        'kmh_announcement_field_category' => 'Kategori',
        'kmh_announcement_field_target' => 'Target Distribusi Email',
        'kmh_announcement_field_target_placeholder' => 'Pilih target pengiriman',
        'kmh_announcement_field_publish_date' => 'Jadwal Publish',
        'kmh_announcement_field_account' => 'Akun UKM',
        'kmh_announcement_field_account_placeholder' => 'Pilih akun',
        'kmh_announcement_field_summary' => 'Ringkasan',
        'kmh_common_save_button' => 'Simpan',
        'kmh_announcement_distribution_info_title' => 'Sistem Distribusi Email:',
        'kmh_announcement_distribution_info_body' => 'Pengumuman untuk semua mahasiswa akan dikirim ke student252@student.unklab.ac.id. Target manual harus diisi alamat email secara langsung. Jika jadwal publish diisi, pengiriman diproses otomatis oleh cron setiap menit.',
        'kmh_announcement_review_email_title' => 'Review Izin Pengumuman ke Email',
        'kmh_announcement_review_email_count_suffix' => 'item menunggu review',
        'kmh_announcement_list_title' => 'Daftar Pengumuman',
        'kmh_announcement_list_count_suffix' => 'total data',
        'kmh_announcement_review_queue_empty' => 'Tidak ada antrean review email.',
        'kmh_announcement_list_empty' => 'Belum ada pengumuman.',
        'kmh_announcement_list_filter_empty' => 'Tidak ada pengumuman yang cocok dengan filter.',
        'kmh_announcement_modal_title' => 'Buat Pengumuman Baru',
        'kmh_announcement_modal_subtitle' => 'Lengkapi detail pengumuman dan pilih aksi publikasi.',
        'kmh_announcement_field_manual_recipients' => 'Email Manual',
        'kmh_announcement_field_manual_recipients_placeholder' => 'Pisahkan email dengan koma atau baris baru',
        'kmh_announcement_field_content' => 'Konten Pengumuman',
        'kmh_announcement_field_content_placeholder' => 'Tulis konten pengumuman di sini...',
        'kmh_announcement_field_publish_datetime' => 'Jadwal Publish',
        'kmh_announcement_field_publish_datetime_placeholder' => 'dd/mm/yyyy, --:--',
        'kmh_announcement_save_draft_button' => 'Simpan sebagai Draft',
        'kmh_announcement_publish_now_button' => 'Publikasikan Sekarang',
        'kmh_announcement_queue_title' => 'Antrian Email Terjadwal',
        'kmh_announcement_queue_count_suffix' => 'item menunggu kirim',
        'kmh_announcement_queue_empty' => 'Tidak ada antrian email terjadwal.',
        'kmh_announcement_sent_title' => 'Email Terkirim',
        'kmh_announcement_sent_count_suffix' => 'item sudah terkirim',
        'kmh_announcement_sent_empty' => 'Belum ada email yang terkirim.',
        'kmh_announcement_default_student_recipient_label' => 'Default semua mahasiswa: student252@student.unklab.ac.id',
        'kmh_common_cancel_button' => 'Batal',
        'kmh_common_review_note_placeholder' => 'Catatan (wajib jika tolak/revisi)',
    ],
];
